import type { Amenity, Camping, Terrain, VehicleType } from "@/lib/types";

export const ALL_AMENITIES: Amenity[] = [
  "restrooms",
  "showers",
  "food",
  "fuel",
  "repair",
];

export const ALL_CAMPING_TYPES: Camping[] = [
  "tent",
  "rv30A",
  "rv50A",
  "fullHookup",
  "cabin",
  "groupSite",
  "backcountry",
];

export const ALL_TERRAIN_TYPES: Terrain[] = [
  "sand",
  "rocks",
  "mud",
  "trails",
  "hills",
];

export const ALL_VEHICLE_TYPES: VehicleType[] = [
  "motorcycle",
  "atv",
  "sxs",
  "fullSize",
];

export const US_STATES = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];
