import { type DbPark, transformDbPark } from "@/lib/types";

describe("transformDbPark", () => {
  it("should transform a complete DbPark to Park format", () => {
    const dbPark: DbPark = {
      id: "123",
      name: "Test Park",
      slug: "test-park",
      latitude: 34.0522,
      longitude: -118.2437,
      website: "https://testpark.com",
      phone: "5551234567",
      campingWebsite: null,
      campingPhone: null,
      dayPassUSD: 25,
      milesOfTrails: 50,
      acres: 1000,
      notes: "Great park for off-roading",
      status: "APPROVED",
      submitterId: null,
      submitterName: null,
      averageRating: 4.5,
      averageDifficulty: 3.5,
      averageTerrain: 4.2,
      averageFacilities: 3.8,
      reviewCount: 10,
      averageRecommendedStay: null,
      datesOpen: null,
      contactEmail: null,
      ownership: null,
      permitRequired: null,
      permitType: null,
      membershipRequired: null,
      maxVehicleWidthInches: null,
      flagsRequired: null,
      sparkArrestorRequired: null,
      noiseLimitDBA: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
      terrain: [{ terrain: "sand" }, { terrain: "rocks" }],
      amenities: [{ amenity: "restrooms" }, { amenity: "showers" }],
      camping: [],
      vehicleTypes: [],
      address: {
        id: "addr-1",
        parkId: "123",
        streetAddress: null,
        streetAddress2: null,
        city: "Test City",
        state: "CA",
        zipCode: null,
        county: null,
        latitude: null,
        longitude: null,
      },
    };

    const result = transformDbPark(dbPark);

    expect(result).toEqual({
      id: "test-park", // slug is used as id
      name: "Test Park",
      address: {
        streetAddress: undefined,
        streetAddress2: undefined,
        city: "Test City",
        state: "CA",
        zipCode: undefined,
        county: undefined,
        latitude: undefined,
        longitude: undefined,
      },
      coords: { lat: 34.0522, lng: -118.2437 },
      website: "https://testpark.com",
      phone: "5551234567",
      campingWebsite: undefined,
      campingPhone: undefined,
      dayPassUSD: 25,
      milesOfTrails: 50,
      acres: 1000,
      notes: "Great park for off-roading",
      terrain: ["sand", "rocks"],
      amenities: ["restrooms", "showers"],
      camping: [],
      vehicleTypes: [],
      averageRating: 4.5,
      averageDifficulty: 3.5,
      averageTerrain: 4.2,
      averageFacilities: 3.8,
      reviewCount: 10,
    });
  });

  it("should handle null values by converting to undefined", () => {
    const dbPark: DbPark = {
      id: "123",
      name: "Minimal Park",
      slug: "minimal-park",
      latitude: null,
      longitude: null,
      website: null,
      phone: null,
      campingWebsite: null,
      campingPhone: null,
      dayPassUSD: null,
      milesOfTrails: null,
      acres: null,
      notes: null,
      status: "APPROVED",
      submitterId: null,
      submitterName: null,
      averageRating: null,
      averageDifficulty: null,
      averageTerrain: null,
      averageFacilities: null,
      reviewCount: 0,
      averageRecommendedStay: null,
      datesOpen: null,
      contactEmail: null,
      ownership: null,
      permitRequired: null,
      permitType: null,
      membershipRequired: null,
      maxVehicleWidthInches: null,
      flagsRequired: null,
      sparkArrestorRequired: null,
      noiseLimitDBA: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
      terrain: [],
      amenities: [],
      camping: [],
      vehicleTypes: [],
      address: {
        id: "addr-2",
        parkId: "123",
        streetAddress: null,
        streetAddress2: null,
        city: null,
        state: "TX",
        zipCode: null,
        county: null,
        latitude: null,
        longitude: null,
      },
    };

    const result = transformDbPark(dbPark);

    expect(result).toEqual({
      id: "minimal-park",
      name: "Minimal Park",
      address: {
        streetAddress: undefined,
        streetAddress2: undefined,
        city: undefined,
        state: "TX",
        zipCode: undefined,
        county: undefined,
        latitude: undefined,
        longitude: undefined,
      },
      coords: undefined,
      website: undefined,
      phone: undefined,
      campingWebsite: undefined,
      campingPhone: undefined,
      dayPassUSD: undefined,
      milesOfTrails: undefined,
      acres: undefined,
      notes: undefined,
      terrain: [],
      amenities: [],
      camping: [],
      vehicleTypes: [],
      averageRating: undefined,
      averageDifficulty: undefined,
      averageTerrain: undefined,
      averageFacilities: undefined,
      reviewCount: 0,
    });
  });

  it("should not include coords if only latitude is present", () => {
    const dbPark: DbPark = {
      id: "123",
      name: "Park",
      slug: "park",
      latitude: 34.0522,
      longitude: null,
      website: null,
      phone: null,
      campingWebsite: null,
      campingPhone: null,
      dayPassUSD: null,
      milesOfTrails: null,
      acres: null,
      notes: null,
      status: "APPROVED",
      submitterId: null,
      submitterName: null,
      averageRating: null,
      averageDifficulty: null,
      averageTerrain: null,
      averageFacilities: null,
      reviewCount: 0,
      averageRecommendedStay: null,
      datesOpen: null,
      contactEmail: null,
      ownership: null,
      permitRequired: null,
      permitType: null,
      membershipRequired: null,
      maxVehicleWidthInches: null,
      flagsRequired: null,
      sparkArrestorRequired: null,
      noiseLimitDBA: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
      terrain: [],
      amenities: [],
      camping: [],
      vehicleTypes: [],
      address: {
        id: "addr-3",
        parkId: "123",
        streetAddress: null,
        streetAddress2: null,
        city: null,
        state: "CA",
        zipCode: null,
        county: null,
        latitude: null,
        longitude: null,
      },
    };

    const result = transformDbPark(dbPark);
    expect(result.coords).toBeUndefined();
  });

  it("should not include coords if only longitude is present", () => {
    const dbPark: DbPark = {
      id: "123",
      name: "Park",
      slug: "park",
      latitude: null,
      longitude: -118.2437,
      website: null,
      phone: null,
      campingWebsite: null,
      campingPhone: null,
      dayPassUSD: null,
      milesOfTrails: null,
      acres: null,
      notes: null,
      status: "APPROVED",
      submitterId: null,
      submitterName: null,
      averageRating: null,
      averageDifficulty: null,
      averageTerrain: null,
      averageFacilities: null,
      reviewCount: 0,
      averageRecommendedStay: null,
      datesOpen: null,
      contactEmail: null,
      ownership: null,
      permitRequired: null,
      permitType: null,
      membershipRequired: null,
      maxVehicleWidthInches: null,
      flagsRequired: null,
      sparkArrestorRequired: null,
      noiseLimitDBA: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
      terrain: [],
      amenities: [],
      camping: [],
      vehicleTypes: [],
      address: {
        id: "addr-4",
        parkId: "123",
        streetAddress: null,
        streetAddress2: null,
        city: null,
        state: "CA",
        zipCode: null,
        county: null,
        latitude: null,
        longitude: null,
      },
    };

    const result = transformDbPark(dbPark);
    expect(result.coords).toBeUndefined();
  });

  it("should correctly map terrain arrays", () => {
    const dbPark: DbPark = {
      id: "123",
      name: "Park",
      slug: "park",
      latitude: null,
      longitude: null,
      website: null,
      phone: null,
      campingWebsite: null,
      campingPhone: null,
      dayPassUSD: null,
      milesOfTrails: null,
      acres: null,
      notes: null,
      status: "APPROVED",
      submitterId: null,
      submitterName: null,
      averageRating: null,
      averageDifficulty: null,
      averageTerrain: null,
      averageFacilities: null,
      reviewCount: 0,
      averageRecommendedStay: null,
      datesOpen: null,
      contactEmail: null,
      ownership: null,
      permitRequired: null,
      permitType: null,
      membershipRequired: null,
      maxVehicleWidthInches: null,
      flagsRequired: null,
      sparkArrestorRequired: null,
      noiseLimitDBA: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
      terrain: [
        { terrain: "sand" },
        { terrain: "rocks" },
        { terrain: "mud" },
        { terrain: "trails" },
        { terrain: "hills" },
      ],
      amenities: [],
      camping: [],
      vehicleTypes: [],
      address: {
        id: "addr-5",
        parkId: "123",
        streetAddress: null,
        streetAddress2: null,
        city: null,
        state: "CA",
        zipCode: null,
        county: null,
        latitude: null,
        longitude: null,
      },
    };

    const result = transformDbPark(dbPark);
    expect(result.terrain).toEqual(["sand", "rocks", "mud", "trails", "hills"]);
  });

  it("should correctly map amenities arrays", () => {
    const dbPark: DbPark = {
      id: "123",
      name: "Park",
      slug: "park",
      latitude: null,
      longitude: null,
      website: null,
      phone: null,
      campingWebsite: null,
      campingPhone: null,
      dayPassUSD: null,
      milesOfTrails: null,
      acres: null,
      notes: null,
      status: "APPROVED",
      submitterId: null,
      submitterName: null,
      averageRating: null,
      averageDifficulty: null,
      averageTerrain: null,
      averageFacilities: null,
      reviewCount: 0,
      averageRecommendedStay: null,
      datesOpen: null,
      contactEmail: null,
      ownership: null,
      permitRequired: null,
      permitType: null,
      membershipRequired: null,
      maxVehicleWidthInches: null,
      flagsRequired: null,
      sparkArrestorRequired: null,
      noiseLimitDBA: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
      terrain: [],
      amenities: [
        { amenity: "restrooms" },
        { amenity: "showers" },
        { amenity: "food" },
        { amenity: "fuel" },
        { amenity: "repair" },
      ],
      camping: [],
      vehicleTypes: [],
      address: {
        id: "addr-6",
        parkId: "123",
        streetAddress: null,
        streetAddress2: null,
        city: null,
        state: "CA",
        zipCode: null,
        county: null,
        latitude: null,
        longitude: null,
      },
    };

    const result = transformDbPark(dbPark);
    expect(result.amenities).toEqual([
      "restrooms",
      "showers",
      "food",
      "fuel",
      "repair",
    ]);
  });

  it("should use slug as id for URL compatibility", () => {
    const dbPark: DbPark = {
      id: "uuid-12345",
      name: "Park",
      slug: "my-awesome-park",
      latitude: null,
      longitude: null,
      website: null,
      phone: null,
      campingWebsite: null,
      campingPhone: null,
      dayPassUSD: null,
      milesOfTrails: null,
      acres: null,
      notes: null,
      status: "APPROVED",
      submitterId: null,
      submitterName: null,
      averageRating: null,
      averageDifficulty: null,
      averageTerrain: null,
      averageFacilities: null,
      reviewCount: 0,
      averageRecommendedStay: null,
      datesOpen: null,
      contactEmail: null,
      ownership: null,
      permitRequired: null,
      permitType: null,
      membershipRequired: null,
      maxVehicleWidthInches: null,
      flagsRequired: null,
      sparkArrestorRequired: null,
      noiseLimitDBA: null,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
      terrain: [],
      amenities: [],
      camping: [],
      vehicleTypes: [],
      address: {
        id: "addr-7",
        parkId: "uuid-12345",
        streetAddress: null,
        streetAddress2: null,
        city: null,
        state: "CA",
        zipCode: null,
        county: null,
        latitude: null,
        longitude: null,
      },
    };

    const result = transformDbPark(dbPark);
    expect(result.id).toBe("my-awesome-park");
    expect(result.id).not.toBe("uuid-12345");
  });
});
