export const FIELD_DISPLAY_NAMES: Record<string, string> = {
  latitude: "Latitude",
  longitude: "Longitude",
  website: "Website",
  phone: "Phone",
  contactEmail: "Contact Email",
  campingWebsite: "Camping Website",
  campingPhone: "Camping Phone",
  isFree: "Free to Visit",
  dayPassUSD: "Day Pass (USD)",
  vehicleEntryFeeUSD: "Vehicle Entry Fee (USD)",
  riderFeeUSD: "Rider Fee (USD)",
  membershipFeeUSD: "Membership Fee (USD)",
  milesOfTrails: "Miles of Trails",
  acres: "Acres",
  notes: "Description / Notes",
  datesOpen: "Dates Open",
  ownership: "Ownership",
  permitRequired: "Permit Required",
  permitType: "Permit Type",
  membershipRequired: "Membership Required",
  maxVehicleWidthInches: "Max Vehicle Width (inches)",
  flagsRequired: "Whip Flags Required",
  sparkArrestorRequired: "Spark Arrestor Required",
  noiseLimitDBA: "Noise Limit (dBA)",
  "address.streetAddress": "Street Address",
  "address.city": "City",
  "address.zipCode": "ZIP Code",
  "address.county": "County",
  terrain: "Terrain Types",
  amenities: "Amenities",
  camping: "Camping Types",
  vehicleTypes: "Vehicle Types",
};
